config/routes.rb
Rails.application.routes.draw do
	resources :tasks, only: [:index, :create] do

		member do 
			post 'finish'
		end
	end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "tasks#index"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
  validates :body, presence: true

  def finished?
    finished==true
  end

  def finished!
    finished = true
    save!
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
	def index
    @tasks = Task.all
  end

  def create
    @task= Task.new(task_params)
    @task.save
  end

  def finish
  	@task = Task.find(params.require(:id))
    @task.finished!
    render json:{}
  end

private

  def task_params
    params.require(:task).permit(:body, :finished)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
  def get_color_class(task)
    if task.finished?
      color = 'red'
    else
      color = 'black'
    end
    color + ' col-xs-6'
  end

  def get_id(task)
    'it' + task.id.to_s
  end

  def show_button(task)
    if task.finished != 1
      button_tag 'Complete', :id => task.id.to_s, :class => 'btn '
    end
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ToDo</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/_task.html.erb
<table>
<% @tasks.reverse_each do |task| %>
  <tr>
    <td
      id=<%= get_id(task)%>
      class=<%= get_color_class(task)%>
    ><%= task.body %></td>
    <td>
      <%= show_button(task) %>
    </td>
    <% end %>
  </tr>
</table>

app/views/tasks/finish.js.erb
 $('#' + <%= @task.id %> + '_content').css('color', 'red');

app/views/tasks/index.html.erb
<h1>Tasks</h1>
<p><font color="blue", size=3>Add a new task: </font> </p>

<div class="container">
    <div class="row">
    <%= form_tag 'item/create', :method => :put, :remote => true do %>
        <div class="col-md-6">
            <div class="form-group">
                <%= text_field_tag :name, params[:name] %>
            </div>
        </div>
        <div class="col-md-6">
            <div class="form-group">
                <%= submit_tag "Add Item", class: "btn", :name => nil %>
            </div>
        </div>
    <% end %>
    </div>
    <div class="row" id="task">
        <%= render partial: 'task' %>
    </div>
</div>




<!--
<%= form_for :task, url: tasks_path do |form| %>
    <table>
      <tbody>
      <tr>
        <td>
          <div class="field">
            <%= form.label :text %>
            <%= form.text_field :body, id: :task_text %>
          </div>
           <div class="actions">
            <%= form.submit %>
          </div>
        </td>
        </tr>
      </tbody>
    </table>
<% end %> 

<table>
  <tbody>
    <% @tasks.each do |task| %>
    <tr>
      <td <%= 'id=task' + task.id.to_s %>
          <% if task.finished %>
          <%= 'style=color:#FF0000'%>
          <% end %> >
        <%= task.body %>
      </td>
      <td>
        <button type="button" onclick="finishTask(<%= task.id %>)" id=<%= task.id %>> Check </button>
      </td>
    <% end %>
  </tbody>
</table>


<script>
    function finishTask(id) {
        console.log('updating task with id', id);
        $.ajax({
                type: 'POST',
                url: "<%= tasks_path %>/" + id + "/finish",
                contentType: 'application/json',
                success: function (response) {
                    $('#' + id + '_content').css('color', 'red');
                },
                error: function (error){
                    alert(error.responseText);
                }        });
    }
</script> -->